export type Address = {
  addressLine: string | null;
  addressLine2: string | null;
  cityName: string | null;
  regionName: string | null;
  postCode: string | null;
  countryCode: string;
  latitude: number;
  longitude: number;
  countryName: string | null;
  cityOrRegionAndPostCode: string;
  country: string | null;
  hasCity: boolean;
  cityRegion: string;
  hasCityOrRegion: boolean;
  hasValidGeo: boolean;
  hasPostcode: boolean;
  hasRegion: boolean;
  addressLabel: string;
  hasCountry: boolean;
};

export type HeadOffice = {
  id: string | null;
  name: string | null;
  address: Address;
};

export type Analytics = {
  placementsCurrMonth: number;
  placementsPrevMonth: number;
  placementsCurrQrtr: number;
  placementsPrevQrtr: number;
  placementsCurrYear: number;
  placementsPrevYear: number;
  totalPlacements: number;
  billingCurrMonth: number;
  billingPrevMonth: number;
  billingCurrQrtr: number;
  billingPrevQrtr: number;
  billingCurrYear: number;
  billingPrevYear: number;
  totalBillingValue: number;
  openJobsCount: number;
  jobsCurrMonth: number;
  jobsPrevMonth: number;
  jobsCurrQrtr: number;
  jobsPrevQrtr: number;
  jobsCurrYear: number;
  jobsPrevYear: number;
  totalOpportunities: number;
  openOpportunities: number;
  opportunitiesCurrMonth: number;
  opportunitiesPrevMonth: number;
  opportunitiesCurrQrtr: number;
  opportunitiesPrevQrtr: number;
  opportunitiesCurrYear: number;
  opportunitiesPrevYear: number;
  opportunityValueCurrMonth: number;
  opportunityValuePrevMonth: number;
  opportunityValueCurrQrtr: number;
  opportunityValuePrevQrtr: number;
  opportunityValueCurrYear: number;
  opportunityValuePrevYear: number;
  opportunityDealValue: number;
  lostOpportunityValue: number;
  totalJobs: number;
  totalContacts: number;
  avgOfferToPlacementPct: number;
  avgInterviewToOfferPct: number;
  avgOfferToPlacementRatio: number | null;
  avgInterviewToOfferRatio: number | null;
  avgClientRejectRate: number;
  closedJobsPipelineValue: number;
  openJobsPipelineValue: number;
  totalPositionsToFill: number;
  pendingPositionsToFill: number;
  avgPlacementValue: number;
  avgTimeToFillCurrYear: number;
  avgTimeToFillPrevYear: number;
  avgTimeToFillAllTime: number;
  avgInterviewToOfferDays: number;
  avgJobCreatedToSourcedDays: number;
  avgJobCreatedToShortlistDays: number;
  avgJobCreatedToApplicationDays: number;
  avgCVSentToInterviewDays: number;
  avgOfferToPlacementDays: number;
};

export type Company = {
  id: string;
  reference: string;
  name: string;
  imageUrl: string | null;
  description: string | null;
  headOffice: HeadOffice;
  website: string;
  email: string;
  phone: string;
  faxNo: string;
  facebook: string | null;
  linkedIn: string | null;
  twitter: string | null;
  analytics: Analytics;
  industries: string[];
  sectors: Array<{ id: string; name: string }>;
  parent: string | null;
  companySizeCode: string;
  companyTypeId: string;
  distributionListId: string | null;
  employees: number | null;
  client: boolean;
  rating: number;
  createdBySystem: boolean;
  skills: string[];
  openJobs: boolean;
  placements: boolean;
  benefitsPackage: string | null;
  termsAgreed: string | null;
  statusId: string | null;
  ownerId: string;
  ownerName: string;
  status: {
    position: number;
    color: string;
  };
  udfList: any[];
  type: string;
  logoUrl: string | null;
  domain: string | null;
  languages: string | null;
  labels: string[];
  apolloRecord: string | null;
  createdOn: string;
  modifiedOn: string;
  additionalParams: any;
};
